# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'plan_description',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.PlanDescription'),
        ),
    ]
